apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-platform
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    backstage.io/techdocs-ref: dir:https://github.com/kihahu/dendron-notes
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

